project:
  type: website
  output-dir: docs 

website:
  title: "SC-H1-v2026"
  page-footer: "SmartCampus 2026 | Built with Quarto"
  search: true
  navbar:
    title: "SC-H1-v2026"
    background: primary
    left:
      - href: index.qmd
        text: ""
        icon: house-door-fill
      - href: descripcion.qmd
        text: Descripción curso
      - href: objetivos.qmd
        text: Objetivos curso
      - href: journal_club.qmd
        text: Journal Club
      - href: programa_sc_h1_2026.qmd
        text: Programa preliminar SC-H1-v2026
format:
  html:
    theme: flatly
    toc: true
    toc-depth: 3
    css: styles.css
  docx:
    toc: true
    toc-depth: 3
    number-sections: true
    highlight-style: github