---
title: "Descripción del curso SC-H1-v2026"
format:
  html: default
  docx:
    output-file: "Descripcion_H1_v2026.docx"
    output-dir: "docs"
    toc: true
    number-sections: false
editor: visual
---

::: academic-indent
La hidrocefalia, en sus múltiples etiologías, constituye una de las **patologías más frecuentemente abordadas por el neurocirujano**, especialmente en el ámbito pediátrico. No obstante, pese a su elevada relevancia clínica, persisten controversias en relación con su fisiopatología, las estrategias terapéuticas óptimas y los métodos más adecuados para evaluar los resultados de los procedimientos quirúrgicos, como las derivaciones ventriculares o la ventriculostomía endoscópica. Cuando no se trata durante la infancia, puede ocasionar graves consecuencias, incluyendo macrocefalia progresiva, alteraciones cognitivas complejas e incluso la muerte.

En la edad adulta, y especialmente en la **hidrocefalia normotensiva**, el neurocirujano se enfrenta a retos diagnósticos y a la incertidumbre en la indicación terapéutica. Este aspecto es especialmente relevante si consideramos que constituye una de las pocas causas potencialmente tratables de deterioro cognitivo y funcional en mayores de 65 años.

Por otra parte, muchos conceptos tradicionales sobre la naturaleza, funciones y dinámica del líquido cefalorraquídeo (LCR), así como la interpretación de la presión intracraneal (PIC), tienden a simplificarse en exceso, limitando su aplicación clínica. Este curso propone una revisión crítica y actualizada de dichos fundamentos, con el objetivo de facilitar su integración en la práctica diaria.

SmartCampus, desde su inicio, ha estructurado su oferta docente en dos itinerarios formativos: el del **paciente neurocrítico (SC-NCri)** y el de la **hidrocefalia y las alteraciones de la dinámica del LCR (SC-H)**. El curso **SC-H1-v2026** constituye una nueva edición del curso inicial del itinerario de hidrocefalia. La gran cantidad de evidencia científica acumulada en los últimos años hace necesaria una revisión sistemática de sus fundamentos.

En este contexto, el curso actualiza los conocimientos esenciales que los profesionales de la neurocirugía deben revisar para mantener un adecuado nivel de competencia en los principios fisiológicos y fisiopatológicos implicados en su manejo. Este curso está especialmente recomendado para quienes deseen iniciarse o consolidar su formación en este itinerario. Sus contenidos se centran en los fundamentos de la anatomía, fisiología y fisiopatología de la dinámica del LCR, proporcionando una base sólida para la comprensión clínica y la toma de decisiones terapéuticas. Para ello, el programa **SC-H1-v2026** combina contenidos teóricos de actualización con talleres prácticos orientados a la aplicación clínica, facilitando una mejor comprensión de los mecanismos fisiopatológicos y el desarrollo de habilidades en la toma de decisiones.
:::
